index:
  banner_img: images/banner_imgs/index.png
  slogan:
    enable: true
    text: Action starts with Passion, Passion rises with Action.
  auto_excerpt:
    enable: false
navbar:
  blog_title: Punny`s Blog
custom_css: /css/custom.css

post:
  banner_img: /images/banner_imgs/post.png
archive:
  banner_img: /images/banner_imgs/archive.png
  banner_img_height: 70
  banner_mask_alpha: 0.3
category:
  enable: true
  banner_img: /images/banner_imgs/category.jpg
  banner_img_height: 70
  banner_mask_alpha: 0.3
tag:
  enable: true
  banner_img: /images/banner_imgs/tags.png
  banner_img_height: 70
  banner_mask_alpha: 0.3
iconfont: //at.alicdn.com/t/c/font_1736178_k526ubmyhba.css
about:
  enable: true
  banner_img: /images/banner_imgs/about.png  # 设置你的 banner 图片
  banner_img_height: 70
  banner_mask_alpha: 0.3
  avatar: /images/icon/webicon.JPG  # 设置头像图片
  name: "Punny"
  intro: "励志成为一个programmer的coder"
  # 社交媒体图标配置
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/punny520", tip: "GitHub" }
    - { class: "iconfont icon-mail", link: "mailto:contactme@gopunny.com", tip: "contactme@gopunny.com" }

fun_features:
  typing:
    enable: true
    scope: [home]

color:
  # body 背景色
  body_bg_color: "#071330"  # Dark Blue
  body_bg_color_dark: "#071330"  # Dark Blue

  # 顶部菜单背景色
  navbar_bg_color: "#252d38"  # Midnight Blue
  navbar_bg_color_dark: "#252d38"  # Midnight Blue

  # 顶部菜单字体色
  navbar_text_color: "#c3ceda"  # Misty Blue
  navbar_text_color_dark: "#c3ceda"  # Misty Blue

  # 副标题字体色
  subtitle_color: "#c3ceda"  # Misty Blue
  subtitle_color_dark: "#c3ceda"  # Misty Blue

  # 全局字体色
  text_color: "#c3ceda"  # Misty Blue
  text_color_dark: "#c3ceda"  # Misty Blue

  # 全局次级字体色（摘要、简介等位置）
  sec_text_color: "#738fa7"  # Blue Gray
  sec_text_color_dark: "#738fa7"  # Blue Gray

  # 主面板背景色
  board_color: "#0c4160"  # Midnight Blue
  board_color_dark: "#0c4160"  # Midnight Blue

  # 文章正文字体色
  post_text_color: "#c3ceda"  # Misty Blue
  post_text_color_dark: "#c3ceda"  # Misty Blue

  # 文章正文字体色（h1 h2 h3...）
  post_heading_color: "#c3ceda"  # Misty Blue
  post_heading_color_dark: "#c3ceda"  # Misty Blue

  # 文章超链接字体色
  post_link_color: "#738fa7"  # Blue Gray
  post_link_color_dark: "#738fa7"  # Blue Gray

  # 超链接悬浮时字体色
  link_hover_color: "#c3ceda"  # Misty Blue
  link_hover_color_dark: "#c3ceda"  # Misty Blue

  # 超链接悬浮背景色
  link_hover_bg_color: "rgba(115, 143, 167, 0.15)"  # Blue Gray with opacity
  link_hover_bg_color_dark: "rgba(115, 143, 167, 0.15)"  # Blue Gray with opacity

  # 分隔线和表格边线的颜色
  line_color: "#738fa7"  # Blue Gray
  line_color_dark: "#738fa7"  # Blue Gray

  # 滚动条颜色
  scrollbar_color: "#738fa7"  # Blue Gray
  scrollbar_color_dark: "#738fa7"  # Blue Gray
  
  # 滚动条悬浮颜色
  scrollbar_hover_color: "#c3ceda"  # Misty Blue
  scrollbar_hover_color_dark: "#c3ceda"  # Misty Blue

  # 按钮背景色
  button_bg_color: "#738fa7"  # Blue Gray
  button_bg_color_dark: "#738fa7"  # Blue Gray
  
  # 按钮悬浮背景色
  button_hover_bg_color: "#071330"  # Dark Blue
  button_hover_bg_color_dark: "#071330"  # Dark Blue


favicon: /images/icon/webicon.JPG

footer:
  content: 
  statistics:
    enable: true
    source: "busuanzi"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"

dark_mode:
  enable: false
  default: light

code:
  copy_btn: true
  highlight:
    enable: true
    line_number: true
    lib: "highlightjs"
    highlightjs:
      style: "atom-one-dark"
    prismjs:
      style: "default"
      preprocess: true